name: Dockerize the social-media-app

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Docker Image
        run: |
          docker build -t my-node-app:${{ github.sha }} .
          docker images

      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 my-node-app:${{ github.sha }}
          docker ps

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERID}}
          password: ${{ secrets.DOCKERPASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: btarunkumar/social-media-app:latest  # Replace with your Docker Hub repo and image tag

      # Deploy to GitHub Pages for main branch
      - name: Deploy to GitHub Pages (Main)
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: client # The folder where the build artifacts are located

      # Additional deploy steps for feature branches if needed
      - name: Deploy to GitHub Pages (Feature Branch)
        if: startsWith(github.ref, 'refs/heads/feature/')
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: client # The folder where the build artifacts are located
